CREATE DATABASE IF NOT EXISTS carfinder;

USE carfinder;

CREATE TABLE if NOT EXISTS usuarios(
username VARCHAR(30) NOT NULL,
nombre VARCHAR(30) NOT NULL,
apellido VARCHAR(30) NOT NULL,
correo VARCHAR(30) NOT NULL,
ciudad VARCHAR(30) NOT NULL,
PRIMARY KEY(username)
)ENGINE=INNODB;

CREATE TABLE if NOT EXISTS coches(
id INT AUTO_INCREMENT,
marca VARCHAR(30) NOT NULL,
modelo VARCHAR(30) NOT NULL,
serie VARCHAR(30) NOT NULL,
potencia INT NOT NULL,
PRIMARY KEY(id)
)ENGINE=INNODB;

CREATE TABLE if NOT EXISTS anuncios(
id INT AUTO_INCREMENT,
usuario VARCHAR(30) NOT NULL,
precio FLOAT NOT NULL,
coche INT NOT NULL,
km INT NOT NULL,
estado VARCHAR(30) NOT NULL,
ciudad VARCHAR(30) NOT NULL,
descripcion VARCHAR(100) NOT NULL,
color VARCHAR(30) NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(usuario) REFERENCES usuarios(username),
FOREIGN KEY(coche) REFERENCES coches(id)
)ENGINE=INNODB;
